services:
  # 1. Tu API Spring Boot
  backend:
    build: .
    container_name: api_rest_neon
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: neon
      DB_URL: jdbc:postgresql://ep-twilight-waterfall-adh2pm4g-pooler.c-2.us-east-1.aws.neon.tech/pets?sslmode=require
      DB_USER: neondb_owner
      DB_PASS: npg_ciR1In8OvFYW
      # Activamos el perfil 'neon'


  # 2. Frontend PHP
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: php_frontend_neon
    ports:
      - "80:80"
    depends_on:
      - backend