services:
  # 1. Base de datos MySQL
  mysql-db: # postgre_db
    image: mysql:8.0 # postgres:15
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root123 # POSTGRES EN VEZ DE MYSQL
      MYSQL_DATABASE: pets
    ports:
      - "3309:3306" # 5432:5432
    volumes:
      - mysql_data:/var/lib/mysql # postgres_data:/var/lib/postgresql/data
      - ./sql_mysql.sql:/docker-entrypoint-initdb.d/sql_mysql.sql # ./sql_postgre.sql:/docker-entrypoint-initdb.d/init.sql

  # 2. Tu API Spring Boot
  backend:
    build: .
    container_name: api_rest_local
    ports:
      - "8085:8080"
    environment:
      # Aqu√≠ activamos el perfil 'local' que creamos antes
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - mysql-db # postgre_db

  # 3. Frontend PHP
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: php_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data: